@extends('layouts.hr')

@section('title', 'Report Details - HR System')

@php
$generatedAt = $report->generated_at ?? $report->created_at;
$metadata = [
    'Category' => $report->category ?? 'N/A',
    'Period' => $report->period_label,
    'Status' => ucfirst($report->status ?? 'draft'),
    'Total Records' => number_format($report->total_records ?? 0),
    'Generated By' => $report->generated_by ?? 'System',
    'Generated At' => $generatedAt ? $generatedAt->format('M d, Y g:i A') : 'Not generated'
];
@endphp

@section('content')
<!-- Page Header -->
<div class="page-header-container mb-4">
  <div class="d-flex justify-content-between align-items-center page-header">
    <div class="d-flex align-items-center">
      <div class="dashboard-logo me-3">
        <img src="{{ asset('assets/images/jetlouge_logo.png') }}" alt="Jetlouge Travels" class="logo-img">
      </div>
      <div>
        <h2 class="fw-bold mb-1">Report Details</h2>
        <p class="text-muted mb-0">{{ $report->title }}</p>
      </div>
    </div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb mb-0">
        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}" class="text-decoration-none">Home</a></li>
        <li class="breadcrumb-item"><a href="{{ route('reports.index') }}" class="text-decoration-none">Reports</a></li>
        <li class="breadcrumb-item active" aria-current="page">Details</li>
      </ol>
    </nav>
  </div>
</div>

<div class="row g-4 mb-4">
  <div class="col-lg-8">
    <div class="card h-100">
      <div class="card-header">
        <h5 class="card-title mb-0">
          <i class="fas fa-file-alt me-2"></i>Report Overview
        </h5>
      </div>
      <div class="card-body">
        <div class="report-summary-box">
          <h6 class="mb-2">Executive Summary</h6>
          <p class="text-muted mb-0">{{ $report->summary ?? 'No summary available for this report yet.' }}</p>
        </div>
        <div class="report-meta-list mt-4">
          @foreach($metadata as $label => $value)
            <div class="report-meta-row">
              <span class="text-muted">{{ $label }}</span>
              <span class="fw-semibold">{{ $value }}</span>
            </div>
          @endforeach
        </div>
      </div>
    </div>
  </div>
  <div class="col-lg-4">
    <div class="card h-100">
      <div class="card-header">
        <h5 class="card-title mb-0">
          <i class="fas fa-bolt me-2"></i>Actions
        </h5>
      </div>
      <div class="card-body d-flex flex-column gap-3">
        <a href="{{ route('reports.index') }}" class="btn btn-view-balance">
          <i class="fas fa-arrow-left me-2"></i>Back to Reports
        </a>
        @if($report->file_path)
          <a href="{{ asset('storage/' . $report->file_path) }}" class="btn btn-primary" target="_blank" rel="noopener">
            <i class="fas fa-file-arrow-up me-2"></i>Open Report File
          </a>
        @else
          <button class="btn btn-outline-secondary report-action-btn" disabled>
            <i class="fas fa-file-arrow-up me-2"></i>No File Available
          </button>
        @endif
      </div>
    </div>
  </div>
</div>

@push('styles')
<style>
.report-summary-box {
  background: #f7f9fc;
  border-radius: 12px;
  padding: 16px 18px;
  border: 1px solid #e3e8f1;
}

.report-meta-list {
  display: grid;
  gap: 12px;
}

.report-meta-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 14px;
  background: #ffffff;
  border-radius: 10px;
  border: 1px solid rgba(0, 0, 0, 0.06);
  box-shadow: 0 2px 10px rgba(0, 0, 0, 0.04);
}

.btn-view-balance {
  background: linear-gradient(135deg, #1f5fbf, #193f91);
  color: #ffffff;
  border: none;
  border-radius: 6px;
  padding: 6px 14px;
  font-size: 0.85rem;
  font-weight: 600;
  box-shadow: 0 4px 10px rgba(25, 63, 145, 0.3);
}

.btn-view-balance:hover,
.btn-view-balance:focus {
  color: #ffffff;
  background: linear-gradient(135deg, #235fce, #1a4fb5);
  box-shadow: 0 6px 14px rgba(25, 63, 145, 0.35);
}

.report-action-btn,
.btn-view-balance {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1rem;
}
</style>
@endpush

@endsection
