<?php

namespace App\Http\Controllers;

use App\Models\Report;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class ReportController extends Controller
{
    /**
     * Display the reports dashboard.
     */
    public function index()
    {
        $reports = Report::orderByDesc('generated_at')
            ->orderByDesc('created_at')
            ->get();

        $reportStats = [
            'total_reports' => $reports->count(),
            'generated_reports' => $reports->where('status', 'generated')->count(),
            'draft_reports' => $reports->where('status', 'draft')->count(),
            'scheduled_reports' => $reports->where('status', 'scheduled')->count(),
            'total_records' => $reports->sum('total_records')
        ];

        return view('reports.index', compact('reports', 'reportStats'));
    }

    /**
     * Display a single report.
     */
    public function show(Report $report)
    {
        return view('reports.show', compact('report'));
    }

    /**
     * Store a new report record.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'category' => ['required', 'string', 'max:100'],
            'period_start' => ['nullable', 'date'],
            'period_end' => ['nullable', 'date', 'after_or_equal:period_start'],
            'summary' => ['nullable', 'string', 'max:1000'],
        ]);

        $userName = Auth::user()->name ?? Auth::user()->email ?? 'System';

        Report::create([
            'title' => $validated['title'],
            'category' => $validated['category'],
            'period_start' => $validated['period_start'] ?? null,
            'period_end' => $validated['period_end'] ?? null,
            'summary' => $validated['summary'] ?? null,
            'status' => 'generated',
            'generated_by' => $userName,
            'generated_at' => now(),
            'total_records' => 0,
            'file_path' => null,
        ]);

        return redirect()->route('reports.index')
            ->with('success', 'Report created successfully.');
    }

    /**
     * Export report summary to CSV.
     */
    public function export()
    {
        $reports = Report::orderByDesc('generated_at')
            ->orderByDesc('created_at')
            ->get();

        $filename = 'reports-summary-' . Str::slug(now()->format('Y-m-d-His')) . '.csv';

        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ];

        $callback = function () use ($reports) {
            $handle = fopen('php://output', 'w');
            fputcsv($handle, ['Title', 'Category', 'Period', 'Status', 'Total Records', 'Generated By', 'Generated At']);

            foreach ($reports as $report) {
                $generatedAt = $report->generated_at ?? $report->created_at;
                fputcsv($handle, [
                    $report->title,
                    $report->category,
                    $report->period_label,
                    $report->status,
                    $report->total_records,
                    $report->generated_by,
                    $generatedAt ? $generatedAt->format('Y-m-d H:i:s') : null,
                ]);
            }

            fclose($handle);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Update a report record.
     */
    public function update(Request $request, Report $report)
    {
        $validated = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'category' => ['required', 'string', 'max:100'],
            'period_start' => ['nullable', 'date'],
            'period_end' => ['nullable', 'date', 'after_or_equal:period_start'],
            'summary' => ['nullable', 'string', 'max:1000'],
            'status' => ['nullable', Rule::in(['generated', 'draft', 'scheduled'])],
        ]);

        $report->update($validated);

        return redirect()->route('reports.index')
            ->with('success', 'Report updated successfully.');
    }

    /**
     * Delete a report record.
     */
    public function destroy(Report $report)
    {
        $report->delete();

        return redirect()->route('reports.index')
            ->with('success', 'Report deleted successfully.');
    }
}
