<?php

namespace App\Http\Controllers;

use App\Models\Report;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Illuminate\Validation\Rule;

class ReportController extends Controller
{
    /**
     * Display the reports dashboard.
     */
    public function index()
    {
        if (!$this->ensureReportsTableExists()) {
            $reports = collect();
            $reportStats = [
                'total_reports' => 0,
                'generated_reports' => 0,
                'draft_reports' => 0,
                'scheduled_reports' => 0,
                'total_records' => 0,
            ];

            return view('reports.index', compact('reports', 'reportStats'))
                ->with('error', 'Reports table is missing. Please run migrations on the server.');
        }

        $reports = Report::orderByDesc('generated_at')
            ->orderByDesc('created_at')
            ->get();

        $reportStats = [
            'total_reports' => $reports->count(),
            'generated_reports' => $reports->where('status', 'generated')->count(),
            'draft_reports' => $reports->where('status', 'draft')->count(),
            'scheduled_reports' => $reports->where('status', 'scheduled')->count(),
            'total_records' => $reports->sum('total_records')
        ];

        return view('reports.index', compact('reports', 'reportStats'));
    }

    /**
     * Display a single report.
     */
    public function show($report)
    {
        if (!$this->ensureReportsTableExists()) {
            return redirect()->route('reports.index')
                ->with('error', 'Reports table is missing. Please run migrations on the server.');
        }

        $reportRecord = Report::findOrFail($report);

        return view('reports.show', ['report' => $reportRecord]);
    }

    /**
     * Store a new report record.
     */
    public function store(Request $request)
    {
        if (!$this->ensureReportsTableExists()) {
            return redirect()->route('reports.index')
                ->with('error', 'Reports table is missing. Please run migrations on the server.');
        }

        $validated = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'category' => ['required', 'string', 'max:100'],
            'period_start' => ['nullable', 'date'],
            'period_end' => ['nullable', 'date', 'after_or_equal:period_start'],
            'summary' => ['nullable', 'string', 'max:1000'],
        ]);

        $userName = Auth::user()->name ?? Auth::user()->email ?? 'System';

        Report::create([
            'title' => $validated['title'],
            'category' => $validated['category'],
            'period_start' => $validated['period_start'] ?? null,
            'period_end' => $validated['period_end'] ?? null,
            'summary' => $validated['summary'] ?? null,
            'status' => 'generated',
            'generated_by' => $userName,
            'generated_at' => now(),
            'total_records' => 0,
            'file_path' => null,
        ]);

        return redirect()->route('reports.index')
            ->with('success', 'Report created successfully.');
    }

    /**
     * Export report summary to CSV.
     */
    public function export()
    {
        if (!$this->ensureReportsTableExists()) {
            return redirect()->route('reports.index')
                ->with('error', 'Reports table is missing. Please run migrations on the server.');
        }

        $reports = Report::orderByDesc('generated_at')
            ->orderByDesc('created_at')
            ->get();

        $filename = 'reports-summary-' . Str::slug(now()->format('Y-m-d-His')) . '.csv';

        $headers = [
            'Content-Type' => 'text/csv',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ];

        $callback = function () use ($reports) {
            $handle = fopen('php://output', 'w');
            fputcsv($handle, ['Title', 'Category', 'Period', 'Status', 'Total Records', 'Generated By', 'Generated At']);

            foreach ($reports as $report) {
                $generatedAt = $report->generated_at ?? $report->created_at;
                fputcsv($handle, [
                    $report->title,
                    $report->category,
                    $report->period_label,
                    $report->status,
                    $report->total_records,
                    $report->generated_by,
                    $generatedAt ? $generatedAt->format('Y-m-d H:i:s') : null,
                ]);
            }

            fclose($handle);
        };

        return response()->stream($callback, 200, $headers);
    }

    /**
     * Update a report record.
     */
    public function update(Request $request, $report)
    {
        if (!$this->ensureReportsTableExists()) {
            return redirect()->route('reports.index')
                ->with('error', 'Reports table is missing. Please run migrations on the server.');
        }

        $validated = $request->validate([
            'title' => ['required', 'string', 'max:255'],
            'category' => ['required', 'string', 'max:100'],
            'period_start' => ['nullable', 'date'],
            'period_end' => ['nullable', 'date', 'after_or_equal:period_start'],
            'summary' => ['nullable', 'string', 'max:1000'],
            'status' => ['nullable', Rule::in(['generated', 'draft', 'scheduled'])],
        ]);

        $reportRecord = Report::findOrFail($report);
        $reportRecord->update($validated);

        return redirect()->route('reports.index')
            ->with('success', 'Report updated successfully.');
    }

    /**
     * Delete a report record.
     */
    public function destroy($report)
    {
        if (!$this->ensureReportsTableExists()) {
            return redirect()->route('reports.index')
                ->with('error', 'Reports table is missing. Please run migrations on the server.');
        }

        $reportRecord = Report::findOrFail($report);
        $reportRecord->delete();

        return redirect()->route('reports.index')
            ->with('success', 'Report deleted successfully.');
    }

    private function ensureReportsTableExists(): bool
    {
        try {
            if (!Schema::hasTable('reports')) {
                Schema::create('reports', function (Blueprint $table) {
                    $table->id();
                    $table->string('title');
                    $table->string('category')->index();
                    $table->date('period_start')->nullable();
                    $table->date('period_end')->nullable();
                    $table->string('status')->default('draft')->index();
                    $table->string('generated_by')->nullable();
                    $table->dateTime('generated_at')->nullable()->index();
                    $table->text('summary')->nullable();
                    $table->unsignedInteger('total_records')->default(0);
                    $table->string('file_path')->nullable();
                    $table->timestamps();
                });
            }
        } catch (\Exception $e) {
            \Log::error('Reports table creation error: ' . $e->getMessage());
            return false;
        }

        return Schema::hasTable('reports');
    }
}
